on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $BLAH and $TITLE and then $BODY
        env:
          NUMBER: ${{ github.event.issue.number }}
          BLAH: ${{ github.actor }}
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}